### ISSUE TITLE
Editor Preview & Runtime Procedural ?

### ISSUE THREAD

**Issue by melMass** [eliemichel/BMeshUnity#1]
Hi Elié,

First thanks a lot for BMeshUnity!!
I'm trying the samples and they all work at runtime but not in the Editor. I'm not sure how mesh can be not `null` in the samples as it's created in the Start function? I might have missed something.

Also, can BMesh be used for runtime procedural mesh creation? If so should I set the InMesh filter each time I update the mesh components?

Thanks

**Comment by melMass** [comment]
Ok so for the Editor part, I can create a custom editor for my script to update the mesh whenever I need, it works well.
A simple way to test is to add `[ContextMenu("Generate Mesh")]` right before Start() and then you can right-click on the script in the inspector > Generate Mesh.
But doing so still does not give me the Editor debug preview from the Readme, but rather the final mesh.

**Comment by melMass** [comment]
Sorry I'm switching back to Unity after 2 years on Unreal and I'm rediscovering a lot 😉

**Comment by eliemichel** [comment]
In the editor the `Start` function is not called by default, because MonoBehavior scripts are usually meant for runtime only. If you want it to run in the Editor, you can simply add `[ExecuteInEditMode]` before the class declaration:

```
[ExecuteInEditMode]
public class MyMeshGenerator : MonoBehaviour
{
//...
}
```

BMeshUnity can of course be used for runtime creation, it is even it's primary goal! You must indeed call `SetInMeshFilter` every time you update the mesh to convert it to Unity representation. You do all your generation steps using BMesh and once it is ready, you call SetInMeshFilter to "validate" it and make it visible in the game.

**Comment by eliemichel** [comment]
> 
> Sorry I'm switching back to Unity after 2 years on Unreal and I'm rediscovering a lot 😉

Welcome back ^^What decided you to switch back if I may?

**Comment by melMass** [comment]
I went a bit more complicated road (serialized fields & Getter/Setters) but it works well.
For me `BMeshUnity.DrawGizmos` still doesn't seem to work as expected.
I'm cleaning the sample I've made so it will be easier to talk around 😄 

About the switch, it's not a full one, but I think I will use Unity more than UE overall. There's is some stuff I love about UE and likewise for Unity but UE is too bloated IMHO. For a long-lasting project, it's less of a problem as you can recreate what you want from scratch in C++ and disable everything you don't need but for a smaller project, the whole system is too cumbersome IMHO. 
I feel a lot more in control in Unity, the package system is great, it's way easier than UE to use with a VCS. I use it mainly for Virtual Production and the fact that it's so easy to extend the Editor is another huge factor.
I love Unreal and it really opened my mind on a lot of things but after fighting with it's UI & it's build/plugin system for too long I decided to give Unity a go since Quarantine and the new version is filling a lot of the issues I had when I left it.

**Comment by melMass** [comment]
### Here are the repro classes
[BMesh Unity Sample - Gist](https://gist.github.com/melMass/51df91f4880fac4f07dfb6ee3217a403)
### Preview
As you can see in Editor I'm not seeing `BMeshUnity.DrawGizmos`
![](https://i.imgur.com/OZcj63Q.gif)

**Comment by melMass** [comment]
.... Je n'avais pas activé les gizmos.... 🤦‍♂️ 
![I'm dumb...](https://i.imgur.com/eBWujAC.gif)

**Comment by melMass** [comment]
Thanks :)

**Comment by eliemichel** [comment]
Aha great problem solved. ^^ Ok about Unreal it seems to match my experience, way too much overhead in the creation process to use it for experiments or small scale projects while Unity is very reliable.
