### ISSUE TITLE
Continue to add to to bmesh after meshfilter?

### ISSUE THREAD

**Issue by yosun** [eliemichel/BMeshUnity#18]
Is it possible to continue to add to bmesh after `BMeshUnity.SetInMeshFilter(mesh, MakeMeshIndependent());` 

If not - is it possible to re-initialize it, so that it can generate a continuous result for the meshfilter?

**Comment by eliemichel** [comment]
You can continue manipulating the bmesh after `SetInMeshFilter`, only you need to call `SetInMeshFilter` again each time you want the actual rendered mesh to be updated ;)
