### ISSUE TITLE
[Proposal]: Separate Vertex, Edge, Loop, and Face in to their own files

### ISSUE THREAD

**Issue by MechWarrior99** [eliemichel/BMeshUnity#7]
### Summary
Move the Vertex, Edge, Loop, and Face classes that are nested in the BMesh class in to their own classes and files.

### Motivation
It would make the BMesh class smaller and easier to read and edit, and allows for easier editing and reading of multiple classes at once. Using the BMesh API currently requires additional boilerplate because it requires you to either declare a static using of the BMesh class, or preface every reference with `BMesh.` (eg `BMesh.Vertex`).
The current implementation also does not follow the  C# [design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/nested-types) making it looks less consistent, clean, and intuitive.

### Drawbacks
This is a breaking change, if anyone were referencing the nested types directly (eg `BMesh.Vertex`) they would need to change the usage from `BMesh.Vertex` to just `Vertex`.

I would be more than willing to make a PR for this, but thought it better to make an issue for it for easier discussion first.

**Comment by eliemichel** [comment]
Maybe the best way to minimize the fix required by breaking changes would be to put all classes in a namespace called `BMesh`. This way `BMesh.Vertex` remains valid, `using static BMesh` can be changed into `using BMesh` when one uses it.

So feel free to PR such a change, I'll be happy to merge it and have this code be more idiomatic!

**Comment by MechWarrior99** [comment]
> Maybe the best way to minimize the fix required by breaking changes would be to put all classes in a namespace called `BMesh`. This way `BMesh.Vertex` remains valid, `using static BMesh` can be changed into `using BMesh` when one uses it.
> 
> So feel free to PR such a change, I'll be happy to merge it and have this code be more idiomatic!

I think a namespace is a good idea, but doing so just moves the breaking change to people that use `using static BMesh`, naming the namespace `BMesh` also invalidates any the direct references to the `BMesh` class such as `BMesh mesh = new BMesh()`, so perhaps a different namespace name? Or just none at all?

**Comment by eliemichel** [comment]
Let's call it `BMeshUnity` then. And yes we will break things anyways. As a transition measure, we can add a public alias `Vertex = BMeshUnity.Vertex` in `BMeshUnity.BMesh` (idk if the keyword `using` makes it a public alias, otherwise we can define a derived class `public class Vertex : public BMeshUnity.BMesh {}`.
